### ISSUE TITLE
feat(Logging): 

### ISSUE THREAD

**Issue by nokome** [stencila/pyla#3]
Currently, Pyla is using the default logging output e.g. 

```
INFO:stencila.pyla.interpreter:Not executing CodeChunk without AST: foo(
```

When running Pyla from Executa (via the `StdioClient`) the logs get captured (from the Pyla child process)  e.g. when using `executa repl --debug`

![image](https://user-images.githubusercontent.com/1152336/70584305-9658ef80-1c25-11ea-86fb-ad4a14256b2f.png)

However, if log data was output as newline delimited JSON as `logga` does (when stderr is non-TTY) then we could do better filtering and analysis of those aggregated logs e.g

```json
{"level": 3, "tag": "stencila.pyla.interpreter", "message": "Not executing CodeChunk without AST: foo("}
```

**Comment by beneboy** [comment]
Just drop in something like https://github.com/thangbn/json-logging-python ?

**Comment by nokome** [comment]
That seems like a fairy heavy weight dependency to then have to configure to `json.dumps` the same dictionary as `logga`. Why not just write a simple custom formatter class? e.g.

```py
class JsonFormatter(logging.Formatter):
  def format(self, record):
        return json.dumps({
          'time':...,
          'level': ...,
          'tag': 'pyla'
          'message': record.message,
        })

looging.setFormatter(JsonFormatter())
```

**Comment by beneboy** [comment]
Yep that is my preferred approach, just playing devil's advocate here and at least researching the alternatives to make sure that's the best thing to do.
