### ISSUE TITLE
fix(CodeChunk.duration): According to schema should be seconds not milliseconds

### ISSUE THREAD

**Issue by nokome** [stencila/pyla#7]
In Schema, `CodeChunk.duration` is documented as seconds: https://github.com/stencila/schema/blob/master/schema/CodeChunk.schema.yaml#L89.

But here, it is calculated as milliseconds:

https://github.com/stencila/pyla/blob/a6de9fc3a8801fda04a0ce5ac2b12659f5977580/stencila/pyla/interpreter.py#L397

We should make them consistent by changing one or the other. I personally think more people are familiar with seconds, so would prefer to to stay with that.

**Comment by beneboy** [comment]
Closed in cfbc1dc
